@server = 127.0.0.1:62354

# request get example
GET {{@server}}/api/v1/resource

###
# request post example
POST http://{{server}}/users
Content-Type: application/json
Accept: application/json

{
  "username": "example_user",
  "email": "example@example.com",
  "password": "password123"
}

###
# request put example
PUT {{@server}}/api/v1/resource/1
Content-Type: application/json
Accept: application/json
{
    "name": "updated_example",
    "value": 100
}

###
# request delete example
DELETE {{@server}}/api/v1/resource/1